"""
JFK / Assassination Complex — Expansion layer for Intel Console.

Maps the assassination nexus: the intelligence–organized crime–political triangle
that enabled the JFK assassination and its cover-up, extending to RFK and MLK.
This is the foundational deep state event — where intelligence agencies,
organized crime, and political power structures demonstrated the ability
to eliminate a sitting president and control the investigation.

Entities (~29): CIA officers (Allen Dulles, John McCone, David Atlee Phillips,
E. Howard Hunt), alleged actors (Oswald, Ruby), New Orleans nexus (Shaw, Ferrie,
Banister, Garrison), organized crime (Marcello, Trafficante, Giancana),
intelligence handler (George de Mohrenschildt), journalist (Dorothy Kilgallen),
investigations (Warren Commission, HSCA, ARRB), programs (Operation Mongoose,
ZR/RIFLE, Operation 40), RFK/MLK assassinations.

EXISTING ENTITIES (referenced by name, NOT duplicated):
  CIA [85], FBI [87], Mossad [88], J. Edgar Hoover [16],
  James Angleton [17], Richard Helms [28], Church Committee [338]

Evidence tiers:
  documented = congressional record, court filing, FOIA, official government doc
  credible   = quality investigative journalism, on-record testimony, academic research
  inference  = pattern-based conclusion from documented facts
  speculative = theory requiring further evidence
"""

# ============================================================
# SOURCES — IDs 576-614
# ============================================================

SOURCES = [
    # --- Warren Commission / Official Record ---
    {
        "id": 576,
        "title": "Report of the President's Commission on the Assassination of President Kennedy (Warren Commission Report)",
        "url": "https://www.archives.gov/research/jfk/warren-commission-report",
        "source_type": "government",
        "year": 1964,
    },
    {
        "id": 577,
        "title": "HSCA Final Report, Vol. I — Findings and Recommendations",
        "url": "https://www.archives.gov/research/jfk/select-committee-report",
        "source_type": "congressional",
        "year": 1979,
    },
    {
        "id": 578,
        "title": "HSCA Final Report, Vol. V — Organized Crime and the Assassination",
        "url": "https://history-matters.com/archive/jfk/hsca/report/html/HSCA_Report_0173a.htm",
        "source_type": "congressional",
        "year": 1979,
    },
    # --- Church Committee / CIA Assassination Plots ---
    {
        "id": 579,
        "title": "Church Committee Interim Report — Alleged Assassination Plots Involving Foreign Leaders",
        "url": "https://www.intelligence.senate.gov/sites/default/files/94465.pdf",
        "source_type": "congressional",
        "year": 1975,
    },
    {
        "id": 580,
        "title": "CIA Inspector General Report on Plots to Assassinate Fidel Castro (1967, declassified 1993)",
        "url": "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB222/index.htm",
        "source_type": "government",
        "year": 1967,
    },
    # --- ARRB / Records Act ---
    {
        "id": 581,
        "title": "Assassination Records Review Board — Final Report",
        "url": "https://www.archives.gov/research/jfk/review-board/report",
        "source_type": "government",
        "year": 1998,
    },
    {
        "id": 582,
        "title": "President John F. Kennedy Assassination Records Collection Act of 1992",
        "url": "https://www.archives.gov/research/jfk/jfk-act",
        "source_type": "government",
        "year": 1992,
    },
    # --- Key Books / Investigative Journalism ---
    {
        "id": 583,
        "title": "Jim Garrison — On the Trail of the Assassins",
        "url": "https://archive.org/details/ontrailofassassi00garr",
        "source_type": "journalism",
        "author": "Jim Garrison",
        "year": 1988,
    },
    {
        "id": 584,
        "title": "James W. Douglass — JFK and the Unspeakable: Why He Died and Why It Matters",
        "url": "https://en.wikipedia.org/wiki/JFK_and_the_Unspeakable",
        "source_type": "academic",
        "author": "James W. Douglass",
        "year": 2008,
    },
    {
        "id": 585,
        "title": "David Talbot — The Devil's Chessboard: Allen Dulles, the CIA, and the Rise of America's Secret Government",
        "url": "https://en.wikipedia.org/wiki/The_Devil%27s_Chessboard",
        "source_type": "journalism",
        "author": "David Talbot",
        "year": 2015,
    },
    {
        "id": 586,
        "title": "Jefferson Morley — The Ghost: The Secret Life of CIA Spymaster James Jesus Angleton",
        "url": "https://en.wikipedia.org/wiki/The_Ghost_(Morley_book)",
        "source_type": "journalism",
        "author": "Jefferson Morley",
        "year": 2017,
    },
    {
        "id": 587,
        "title": "Peter Dale Scott — Deep Politics and the Death of JFK",
        "url": "https://en.wikipedia.org/wiki/Peter_Dale_Scott",
        "source_type": "academic",
        "author": "Peter Dale Scott",
        "year": 1993,
    },
    {
        "id": 588,
        "title": "John Newman — Oswald and the CIA: The Documented Truth About the Unknown Relationship",
        "url": "https://en.wikipedia.org/wiki/John_M._Newman",
        "source_type": "academic",
        "author": "John Newman",
        "year": 1995,
    },
    # --- E. Howard Hunt ---
    {
        "id": 589,
        "title": "E. Howard Hunt deathbed confession — Rolling Stone (April 2007)",
        "url": "https://www.rollingstone.com/feature/the-last-confessions-of-e-howard-hunt-76611/",
        "source_type": "journalism",
        "author": "Erik Hedegaard",
        "year": 2007,
    },
    # --- Clay Shaw Trial ---
    {
        "id": 590,
        "title": "State of Louisiana v. Clay L. Shaw — Trial transcript and records",
        "url": "https://www.maryferrell.org/pages/Garrison_Investigation_and_Shaw_Trial.html",
        "source_type": "court",
        "year": 1969,
    },
    {
        "id": 591,
        "title": "CIA admits Clay Shaw was a contact — FOIA release (1992)",
        "url": "https://www.maryferrell.org/pages/Featured_Clay_Shaw.html",
        "source_type": "government",
        "year": 1992,
    },
    # --- Oswald / Intelligence Connections ---
    {
        "id": 592,
        "title": "CIA cable traffic on Oswald — Mexico City station (FOIA releases)",
        "url": "https://www.maryferrell.org/pages/Featured_Oswald_in_Mexico_City.html",
        "source_type": "government",
        "year": 1963,
    },
    {
        "id": 593,
        "title": "George de Mohrenschildt — HSCA testimony and Warren Commission deposition",
        "url": "https://www.maryferrell.org/pages/Featured_George_de_Mohrenschildt.html",
        "source_type": "congressional",
        "year": 1977,
    },
    # --- Organized Crime / CIA-Mafia Plots ---
    {
        "id": 594,
        "title": "Carlos Marcello — BRILAB FBI wiretap transcripts",
        "url": "https://en.wikipedia.org/wiki/Carlos_Marcello",
        "source_type": "government",
        "year": 1981,
    },
    {
        "id": 595,
        "title": "Santos Trafficante — HSCA executive session testimony (1978)",
        "url": "https://www.maryferrell.org/pages/HSCA.html",
        "source_type": "congressional",
        "year": 1978,
    },
    {
        "id": 596,
        "title": "Sam Giancana — CIA-Mafia assassination plots (Church Committee testimony murdered before)",
        "url": "https://en.wikipedia.org/wiki/Sam_Giancana",
        "source_type": "congressional",
        "year": 1975,
    },
    # --- Jack Ruby ---
    {
        "id": 597,
        "title": "Jack Ruby — Warren Commission testimony ('take me to Washington' plea)",
        "url": "https://www.maryferrell.org/showDoc.html?docId=39",
        "source_type": "government",
        "year": 1964,
    },
    # --- NSAM 263 / 273 (Vietnam Policy Reversal) ---
    {
        "id": 598,
        "title": "NSAM 263 — Kennedy withdrawal order from Vietnam (Oct 11, 1963)",
        "url": "https://www.jfklibrary.org/asset-viewer/archives/JFKNSF/346/JFKNSF-346-013",
        "source_type": "government",
        "year": 1963,
    },
    {
        "id": 599,
        "title": "NSAM 273 — LBJ reversal of Vietnam withdrawal (Nov 26, 1963)",
        "url": "https://www.archives.gov/files/declassification/iscap/pdf/2008-003-doc1.pdf",
        "source_type": "government",
        "year": 1963,
    },
    # --- Operation Mongoose / ZR/RIFLE / Operation 40 ---
    {
        "id": 600,
        "title": "Operation Mongoose — declassified documents (National Security Archive)",
        "url": "https://nsarchive2.gwu.edu/nsa/cuba_mis_cri/docs.htm",
        "source_type": "government",
        "year": 1962,
    },
    {
        "id": 601,
        "title": "ZR/RIFLE — Church Committee exposure of CIA assassination program",
        "url": "https://www.maryferrell.org/pages/ZRRIFLE.html",
        "source_type": "congressional",
        "year": 1975,
    },
    {
        "id": 602,
        "title": "Operation 40 — CIA declassified records",
        "url": "https://nsarchive2.gwu.edu/bayofpigs/19610101.pdf",
        "source_type": "government",
        "year": 1961,
    },
    # --- David Atlee Phillips ---
    {
        "id": 603,
        "title": "David Atlee Phillips — HSCA testimony and Kevin Walsh investigation",
        "url": "https://www.maryferrell.org/pages/Featured_David_Phillips.html",
        "source_type": "congressional",
        "year": 1978,
    },
    # --- Dorothy Kilgallen ---
    {
        "id": 604,
        "title": "Mark Shaw — The Reporter Who Knew Too Much: Dorothy Kilgallen and the JFK Assassination",
        "url": "https://en.wikipedia.org/wiki/Dorothy_Kilgallen",
        "source_type": "journalism",
        "author": "Mark Shaw",
        "year": 2016,
    },
    # --- RFK Assassination ---
    {
        "id": 605,
        "title": "LAPD Summary Report — Robert F. Kennedy assassination investigation (1969)",
        "url": "https://en.wikipedia.org/wiki/Assassination_of_Robert_F._Kennedy",
        "source_type": "government",
        "year": 1969,
    },
    {
        "id": 606,
        "title": "Paul Schrade (RFK shooting victim) calls for reinvestigation — CNN (2018)",
        "url": "https://www.cnn.com/2018/06/05/us/rfk-assassination-50th-anniversary",
        "source_type": "journalism",
        "year": 2018,
    },
    # --- MLK Assassination ---
    {
        "id": 607,
        "title": "HSCA Report on the Assassination of Martin Luther King Jr. (1979)",
        "url": "https://www.archives.gov/research/jfk/select-committee-report/part-2",
        "source_type": "congressional",
        "year": 1979,
    },
    {
        "id": 608,
        "title": "King Family Civil Trial — Jowers v. King verdict: 'government agencies were party to the assassination' (1999)",
        "url": "https://www.thekingcenter.org/assassination-civil-trial",
        "source_type": "court",
        "year": 1999,
    },
    # --- Allen Dulles ---
    {
        "id": 609,
        "title": "Allen Dulles — CIA Director (1953–1961), dismissed by Kennedy after Bay of Pigs",
        "url": "https://en.wikipedia.org/wiki/Allen_Dulles",
        "source_type": "other",
        "year": 2024,
    },
    # --- Guy Banister ---
    {
        "id": 610,
        "title": "HSCA Vol. X — Guy Banister investigation (544 Camp Street connection to Oswald)",
        "url": "https://www.maryferrell.org/showDoc.html?docId=800",
        "source_type": "congressional",
        "year": 1979,
    },
    # --- David Ferrie ---
    {
        "id": 611,
        "title": "David Ferrie — Garrison investigation files and CIA connections",
        "url": "https://www.maryferrell.org/pages/Featured_David_Ferrie.html",
        "source_type": "journalism",
        "year": 1967,
    },
    # --- Zapruder Film ---
    {
        "id": 612,
        "title": "Zapruder Film — ARRB acquisition for National Archives (1998)",
        "url": "https://www.archives.gov/research/jfk/zapruder-film",
        "source_type": "government",
        "year": 1963,
    },
    # --- Mary Ferrell Foundation ---
    {
        "id": 613,
        "title": "Mary Ferrell Foundation — JFK document archive (largest digital collection)",
        "url": "https://www.maryferrell.org/",
        "source_type": "other",
        "year": 2003,
    },
    # --- National Archives JFK Collection ---
    {
        "id": 614,
        "title": "National Archives — JFK Assassination Records Collection (ongoing releases through 2023)",
        "url": "https://www.archives.gov/research/jfk",
        "source_type": "government",
        "year": 2023,
    },
]

# ============================================================
# ENTITIES
# ============================================================

ENTITIES = [
    # --- CIA Officers ---
    {
        "name": "Allen Dulles",
        "entity_type": "person",
        "description": "CIA Director 1953–1961. Fired by Kennedy after Bay of Pigs. Appointed to Warren Commission by LBJ — investigated the agency he formerly ran. Key architect of CIA covert operations including MKUltra authorization and Guatemala coup.",
        "aliases": "",
        "metadata": {"role": "CIA Director / Warren Commissioner", "years_active": "1953-1969"},
    },
    {
        "name": "John McCone",
        "entity_type": "person",
        "description": "CIA Director 1961–1965, succeeding Allen Dulles. In office during the Kennedy assassination. Later admitted the CIA withheld information from the Warren Commission about CIA-Mafia assassination plots against Castro.",
        "aliases": "",
        "metadata": {"role": "CIA Director", "years_active": "1961-1965"},
    },
    {
        "name": "David Atlee Phillips",
        "entity_type": "person",
        "description": "CIA Chief of Western Hemisphere Division. Ran anti-Castro propaganda operations. Managed CIA's Mexico City station monitoring of Oswald. HSCA investigated his potential role; former colleague Antonio Veciana identified him as 'Maurice Bishop' who met with Oswald.",
        "aliases": "Maurice Bishop",
        "metadata": {"role": "CIA officer", "years_active": "1950-1975"},
    },
    {
        "name": "E. Howard Hunt",
        "entity_type": "person",
        "description": "CIA officer, Bay of Pigs planner, later Watergate burglar. In 2007 deathbed confession to son Saint John Hunt, named Cord Meyer, David Atlee Phillips, and LBJ as involved in JFK assassination. Described himself as a 'bench warmer' in the plot.",
        "aliases": "Eduardo",
        "metadata": {"role": "CIA officer / Watergate burglar", "years_active": "1949-1975"},
    },
    # --- New Orleans Nexus ---
    {
        "name": "Lee Harvey Oswald",
        "entity_type": "person",
        "description": "Alleged lone assassin of JFK. Former Marine with security clearance who 'defected' to USSR then returned without consequence. Connected to CIA-monitored anti-Castro operations in New Orleans (544 Camp Street). CIA's Mexico City station tracked his movements. HSCA found 'probable conspiracy' beyond the lone gunman conclusion.",
        "aliases": "Alek James Hidell",
        "metadata": {"role": "alleged assassin", "years_active": "1959-1963"},
    },
    {
        "name": "Jack Ruby",
        "entity_type": "person",
        "description": "Dallas nightclub owner who shot Oswald on live television, Nov 24, 1963. Connected to Carlos Marcello's organization and Santos Trafficante. HSCA documented his organized crime ties. Told Warren Commission: 'I have been used for a purpose' and begged to be taken to Washington, implying he could not speak freely in Dallas.",
        "aliases": "Jacob Leon Rubenstein",
        "metadata": {"role": "nightclub owner / Oswald's killer", "years_active": "1947-1967"},
    },
    {
        "name": "Clay Shaw",
        "entity_type": "person",
        "description": "New Orleans businessman and CIA contact (confirmed by CIA in 1992 FOIA release, after decades of denial). Prosecuted by Jim Garrison in 1969 for conspiracy in JFK assassination — acquitted. Garrison's case was ridiculed at the time but CIA connection later verified.",
        "aliases": "Clay Bertrand",
        "metadata": {"role": "CIA contact / Garrison defendant", "years_active": "1948-1974"},
    },
    {
        "name": "David Ferrie",
        "entity_type": "person",
        "description": "Pilot, ex-Eastern Airlines. Connected to Lee Harvey Oswald through Civil Air Patrol. Worked as investigator for Carlos Marcello's attorney. Connected to CIA anti-Castro operations. Found dead in 1967 days after Garrison announced his investigation — ruled natural causes.",
        "aliases": "",
        "metadata": {"role": "pilot / CIA asset / Marcello associate", "years_active": "1955-1967"},
    },
    {
        "name": "Guy Banister",
        "entity_type": "person",
        "description": "Former FBI Special Agent in Charge of Chicago. Ran private detective agency at 544 Camp Street, New Orleans — same building where Oswald distributed pro-Castro leaflets (stamped with that address). Connected to anti-Castro operations, CIA, and ONI.",
        "aliases": "",
        "metadata": {"role": "ex-FBI / private investigator", "years_active": "1934-1964"},
    },
    {
        "name": "Jim Garrison",
        "entity_type": "person",
        "description": "Orleans Parish District Attorney who conducted the only criminal prosecution related to the JFK assassination. Charged Clay Shaw with conspiracy in 1967. Shaw acquitted in 1969, but Garrison's core thesis — CIA involvement — was partially vindicated by later FOIA releases confirming Shaw's CIA connection.",
        "aliases": "",
        "metadata": {"role": "District Attorney", "years_active": "1962-1973"},
    },
    {
        "name": "George de Mohrenschildt",
        "entity_type": "person",
        "description": "Russian-born geologist with extensive intelligence connections (CIA, French intelligence). Befriended Oswald in Dallas and was his primary social handler 1962-63. Found dead of gunshot wound on the day he was contacted by HSCA investigator Gaeton Fonzi in 1977 — ruled suicide.",
        "aliases": "",
        "metadata": {"role": "intelligence asset / Oswald handler", "years_active": "1938-1977"},
    },
    # --- Organized Crime (CIA-Mafia Plots) ---
    {
        "name": "Carlos Marcello",
        "entity_type": "person",
        "description": "Boss of the New Orleans crime family. Deported by Robert Kennedy in 1961, returned illegally. HSCA found credible evidence of his involvement in the JFK assassination. FBI BRILAB wiretaps captured him claiming credit: 'Yeah, I had the son of a bitch killed.' David Ferrie worked for his attorney.",
        "aliases": "Calogero Minacore",
        "metadata": {"role": "organized crime boss", "years_active": "1947-1989"},
    },
    {
        "name": "Santos Trafficante",
        "entity_type": "person",
        "description": "Boss of the Tampa crime family. Participated in CIA-Mafia plots to assassinate Castro (documented by Church Committee). HSCA found credible evidence of his involvement in JFK assassination. His lawyer Frank Ragano claimed Trafficante confessed on his deathbed.",
        "aliases": "Santo Trafficante Jr.",
        "metadata": {"role": "organized crime boss", "years_active": "1954-1987"},
    },
    {
        "name": "Sam Giancana",
        "entity_type": "person",
        "description": "Boss of the Chicago Outfit. Participated in CIA-Mafia plots against Castro (Church Committee documented). Shared mistress Judith Exner with JFK. Murdered in 1975, days before he was scheduled to testify before the Church Committee about CIA assassination plots.",
        "aliases": "Momo",
        "metadata": {"role": "organized crime boss", "years_active": "1957-1975"},
    },
    # --- Dorothy Kilgallen ---
    {
        "name": "Dorothy Kilgallen",
        "entity_type": "person",
        "description": "Prominent journalist and TV personality (What's My Line?). Conducted the only private interview with Jack Ruby during his trial. Told friends she was about to 'break the case wide open.' Found dead Nov 8, 1965 — ruled barbiturate overdose. Her JFK investigation notes were never found.",
        "aliases": "",
        "metadata": {"role": "journalist", "years_active": "1931-1965"},
    },
    # --- Investigations ---
    {
        "name": "Warren Commission",
        "entity_type": "organization",
        "description": "Presidential commission established by LBJ (Nov 29, 1963) to investigate the JFK assassination. Concluded Oswald acted alone. Members included Allen Dulles (fired CIA Director) and Gerald Ford (later president). Relied heavily on FBI investigation overseen by J. Edgar Hoover. Findings challenged by HSCA in 1979.",
        "aliases": "President's Commission on the Assassination of President Kennedy",
        "metadata": {"type": "investigation", "years_active": "1963-1964"},
    },
    {
        "name": "HSCA",
        "entity_type": "organization",
        "description": "House Select Committee on Assassinations (1976-1979). Investigated JFK and MLK assassinations. Concluded JFK was 'probably assassinated as a result of a conspiracy' based on acoustics evidence and witness testimony. Found both the CIA and FBI were deficient in their investigations.",
        "aliases": "House Select Committee on Assassinations",
        "metadata": {"type": "congressional committee", "years_active": "1976-1979"},
    },
    {
        "name": "ARRB",
        "entity_type": "organization",
        "description": "Assassination Records Review Board. Independent federal agency created by the JFK Records Act (1992) to oversee release of assassination records. Released millions of previously classified documents. Found that multiple agencies had withheld relevant records from the Warren Commission.",
        "aliases": "Assassination Records Review Board",
        "metadata": {"type": "federal agency", "years_active": "1994-1998"},
    },
    # --- Programs ---
    {
        "name": "Operation Mongoose",
        "entity_type": "program",
        "description": "CIA covert operation (1961-1962) to overthrow Castro. Authorized by Kennedy administration under Gen. Edward Lansdale. Included sabotage, propaganda, and assassination plots (in coordination with organized crime). Created the operational infrastructure later linked to assassination network.",
        "aliases": "The Cuba Project",
        "metadata": {"type": "covert operation", "years_active": "1961-1962"},
    },
    {
        "name": "ZR/RIFLE",
        "entity_type": "program",
        "description": "CIA 'executive action' (assassination) program revealed by Church Committee. Run by William Harvey under Richard Helms. Recruited foreign assets for 'ichneumon' capability — plausibly deniable assassination. Used as mechanism for CIA-Mafia Castro assassination plots.",
        "aliases": "ZR-RIFLE, Executive Action",
        "metadata": {"type": "assassination program", "years_active": "1961-1963"},
    },
    {
        "name": "Operation 40",
        "entity_type": "program",
        "description": "CIA-sponsored group of anti-Castro Cuban exiles created for Bay of Pigs. Included intelligence, sabotage, and assassination capabilities. Members later connected to Watergate and various covert operations. Operated with organized crime connections.",
        "aliases": "",
        "metadata": {"type": "covert operation", "years_active": "1960-1970"},
    },
    # --- Facilities / Locations ---
    {
        "name": "Dealey Plaza",
        "entity_type": "facility",
        "description": "Site of the JFK assassination in Dallas, Texas (Nov 22, 1963). Warren Commission concluded shots came from Texas School Book Depository. HSCA acoustics evidence suggested additional shooter from the grassy knoll. Now a National Historic Landmark.",
        "aliases": "",
        "metadata": {"location": "Dallas, Texas"},
    },
    # --- Events ---
    {
        "name": "JFK Assassination",
        "entity_type": "event",
        "description": "Assassination of President John F. Kennedy on November 22, 1963 in Dealey Plaza, Dallas. Warren Commission concluded lone gunman (Oswald). HSCA concluded probable conspiracy in 1979. Millions of records still partially classified. The event that made the term 'deep state' necessary.",
        "aliases": "",
        "metadata": {"date": "1963-11-22", "location": "Dallas, Texas"},
    },
    {
        "name": "Robert F. Kennedy",
        "entity_type": "person",
        "description": "U.S. Attorney General (1961-64), U.S. Senator. Aggressively prosecuted organized crime (deported Marcello, pursued Hoffa). Assassinated June 5, 1968 during presidential campaign in Los Angeles. Official account (Sirhan Sirhan as lone gunman) challenged by autopsy evidence showing shots from behind at close range while Sirhan was in front.",
        "aliases": "RFK, Bobby Kennedy",
        "metadata": {"role": "Attorney General / Senator", "years_active": "1961-1968"},
    },
    {
        "name": "RFK Assassination",
        "entity_type": "event",
        "description": "Assassination of Robert F. Kennedy on June 5, 1968 at the Ambassador Hotel, Los Angeles. Sirhan Sirhan convicted. Thomas Noguchi autopsy found fatal shot fired from 1 inch behind right ear — Sirhan was in front of Kennedy. LAPD destroyed evidence. RFK had privately indicated intent to reopen JFK investigation if elected.",
        "aliases": "",
        "metadata": {"date": "1968-06-05", "location": "Los Angeles, California"},
    },
    {
        "name": "Sirhan Sirhan",
        "entity_type": "person",
        "description": "Convicted of RFK assassination. Found in a trance-like state at the scene. His gun held 8 rounds but witnesses and audio analysis suggest 13+ shots fired. No memory of the shooting. Some researchers have investigated possible hypnotic programming (credible — documented MKULTRA capabilities).",
        "aliases": "",
        "metadata": {"role": "convicted assassin", "years_active": "1968"},
    },
    {
        "name": "Martin Luther King Jr.",
        "entity_type": "person",
        "description": "Civil rights leader assassinated April 4, 1968 in Memphis. James Earl Ray convicted but recanted. HSCA found 'likelihood of conspiracy.' In 1999, King family civil trial (Jowers v. King) jury found that 'government agencies were party to the assassination plot.' FBI's COINTELPRO had targeted King for years.",
        "aliases": "MLK",
        "metadata": {"role": "civil rights leader", "years_active": "1955-1968"},
    },
    {
        "name": "MLK Assassination",
        "entity_type": "event",
        "description": "Assassination of Martin Luther King Jr. on April 4, 1968 in Memphis, Tennessee. James Earl Ray pleaded guilty, later recanted. HSCA found 'likelihood of conspiracy.' 1999 King family civil trial jury unanimously found government agencies participated in the assassination plot.",
        "aliases": "",
        "metadata": {"date": "1968-04-04", "location": "Memphis, Tennessee"},
    },
    {
        "name": "James Earl Ray",
        "entity_type": "person",
        "description": "Convicted of MLK assassination after guilty plea. Recanted within days, spent remaining life seeking trial. Escaped convict who traveled internationally on fraudulent passports (suggesting support network). Coretta Scott King and the King family came to believe he was a patsy.",
        "aliases": "",
        "metadata": {"role": "convicted assassin", "years_active": "1968"},
    },
]

# ============================================================
# RELATIONSHIPS
# ============================================================

RELATIONSHIPS = [
    # --- CIA Officers ---
    {
        "source": "Allen Dulles",
        "target": "CIA",
        "type": "directed",
        "tier": "documented",
        "desc": "CIA Director 1953–1961. Fired by Kennedy after Bay of Pigs failure.",
        "sources": [585, 609],
        "year_start": 1953,
        "year_end": 1961,
    },
    {
        "source": "Allen Dulles",
        "target": "Warren Commission",
        "type": "member_of",
        "tier": "documented",
        "desc": "Appointed by LBJ to investigate the assassination — conflict of interest as former CIA Director fired by the victim.",
        "sources": [576, 585],
        "year_start": 1963,
        "year_end": 1964,
    },
    {
        "source": "John McCone",
        "target": "CIA",
        "type": "directed",
        "tier": "documented",
        "desc": "CIA Director during the Kennedy assassination. Later admitted CIA withheld information from Warren Commission.",
        "sources": [576, 581],
        "year_start": 1961,
        "year_end": 1965,
    },
    {
        "source": "David Atlee Phillips",
        "target": "CIA",
        "type": "worked_for",
        "tier": "documented",
        "desc": "Chief of Western Hemisphere Division. Ran anti-Castro propaganda and Mexico City operations including Oswald monitoring.",
        "sources": [603, 588],
        "year_start": 1950,
        "year_end": 1975,
    },
    {
        "source": "E. Howard Hunt",
        "target": "CIA",
        "type": "worked_for",
        "tier": "documented",
        "desc": "CIA officer involved in Guatemala coup, Bay of Pigs, and later Watergate. Deathbed confession implicated CIA colleagues in JFK assassination.",
        "sources": [589],
        "year_start": 1949,
        "year_end": 1970,
    },
    {
        "source": "E. Howard Hunt",
        "target": "JFK Assassination",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Deathbed confession (2007) to son Saint John Hunt: named Cord Meyer, David Atlee Phillips, LBJ as involved. Called himself a 'bench warmer' in the operation.",
        "sources": [589],
        "year_start": 1963,
        "year_end": 1963,
    },
    # --- Lee Harvey Oswald ---
    {
        "source": "Lee Harvey Oswald",
        "target": "JFK Assassination",
        "type": "participated_in",
        "tier": "documented",
        "desc": "Arrested and charged with assassination. Killed by Jack Ruby before trial. Warren Commission concluded he acted alone; HSCA concluded probable conspiracy.",
        "sources": [576, 577],
        "year_start": 1963,
        "year_end": 1963,
    },
    {
        "source": "Lee Harvey Oswald",
        "target": "CIA",
        "type": "connected_to",
        "tier": "credible",
        "desc": "CIA's Mexico City station monitored Oswald. FOIA releases show extensive CIA interest. Former Marine with Russian language training and security clearance who 'defected' to USSR and returned without consequence.",
        "sources": [588, 592, 614],
        "year_start": 1959,
        "year_end": 1963,
    },
    {
        "source": "James Angleton",
        "target": "Lee Harvey Oswald",
        "type": "monitored",
        "tier": "documented",
        "desc": "Angleton's counterintelligence division maintained a file on Oswald. Angleton personally handled CIA's response to the Warren Commission regarding Oswald.",
        "sources": [586, 588],
        "year_start": 1959,
        "year_end": 1963,
    },
    {
        "source": "David Atlee Phillips",
        "target": "Lee Harvey Oswald",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Phillips ran the Mexico City station that monitored Oswald. Antonio Veciana identified Phillips as 'Maurice Bishop' who met with Oswald in Dallas.",
        "sources": [603, 588],
        "year_start": 1963,
        "year_end": 1963,
    },
    # --- Jack Ruby ---
    {
        "source": "Jack Ruby",
        "target": "Lee Harvey Oswald",
        "type": "killed",
        "tier": "documented",
        "desc": "Shot Oswald on live television Nov 24, 1963 in Dallas Police basement, eliminating the only defendant.",
        "sources": [576, 597],
        "year_start": 1963,
        "year_end": 1963,
    },
    {
        "source": "Jack Ruby",
        "target": "Carlos Marcello",
        "type": "connected_to",
        "tier": "credible",
        "desc": "HSCA documented Ruby's organized crime connections to Marcello's network through multiple intermediaries.",
        "sources": [578, 597],
        "year_start": 1947,
        "year_end": 1963,
    },
    {
        "source": "Jack Ruby",
        "target": "Santos Trafficante",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Ruby visited Trafficante in Cuba (1959). HSCA documented their relationship through organized crime networks.",
        "sources": [578, 595],
        "year_start": 1959,
        "year_end": 1963,
    },
    # --- New Orleans Nexus ---
    {
        "source": "Clay Shaw",
        "target": "CIA",
        "type": "worked_for",
        "tier": "documented",
        "desc": "CIA confirmed Shaw was a 'contact' in 1992 FOIA release — after decades of denying any relationship during and after Garrison's prosecution.",
        "sources": [590, 591],
        "year_start": 1948,
        "year_end": 1974,
    },
    {
        "source": "Jim Garrison",
        "target": "Clay Shaw",
        "type": "investigated",
        "tier": "documented",
        "desc": "Garrison prosecuted Shaw for conspiracy in JFK assassination (1967-69). Shaw acquitted. Garrison's core thesis of CIA involvement later partially vindicated.",
        "sources": [583, 590],
        "year_start": 1967,
        "year_end": 1969,
    },
    {
        "source": "David Ferrie",
        "target": "Lee Harvey Oswald",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Both in same Civil Air Patrol unit in New Orleans. Garrison investigation documented their relationship. Ferrie died days after Garrison's investigation became public.",
        "sources": [583, 611],
        "year_start": 1955,
        "year_end": 1963,
    },
    {
        "source": "David Ferrie",
        "target": "Carlos Marcello",
        "type": "worked_for",
        "tier": "credible",
        "desc": "Ferrie worked as investigator for G. Wray Gill, Marcello's attorney. Was in Guatemala with Marcello on the day of the assassination.",
        "sources": [578, 611],
        "year_start": 1961,
        "year_end": 1963,
    },
    {
        "source": "David Ferrie",
        "target": "Clay Shaw",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Connected through anti-Castro operations in New Orleans. Garrison's investigation documented their relationship.",
        "sources": [583, 611],
        "year_start": 1961,
        "year_end": 1967,
    },
    {
        "source": "Guy Banister",
        "target": "FBI",
        "type": "worked_for",
        "tier": "documented",
        "desc": "Former FBI Special Agent in Charge, Chicago field office. After retirement, ran private detective agency involved in anti-Castro operations.",
        "sources": [610],
        "year_start": 1934,
        "year_end": 1955,
    },
    {
        "source": "Guy Banister",
        "target": "Lee Harvey Oswald",
        "type": "connected_to",
        "tier": "credible",
        "desc": "Oswald's pro-Castro leaflets stamped with 544 Camp Street address — Banister's office building. HSCA investigated the connection.",
        "sources": [610, 577],
        "year_start": 1963,
        "year_end": 1963,
    },
    {
        "source": "George de Mohrenschildt",
        "target": "Lee Harvey Oswald",
        "type": "connected_to",
        "tier": "documented",
        "desc": "Befriended Oswald in Dallas 1962-63. Only prominent social contact. Found dead of gunshot the day HSCA investigator Gaeton Fonzi made contact.",
        "sources": [593, 577],
        "year_start": 1962,
        "year_end": 1963,
    },
    {
        "source": "George de Mohrenschildt",
        "target": "CIA",
        "type": "connected_to",
        "tier": "credible",
        "desc": "FOIA releases documented CIA contacts. Had relationship with J. Walton Moore of CIA's Domestic Contacts Division in Dallas.",
        "sources": [593, 614],
        "year_start": 1957,
        "year_end": 1977,
    },
    # --- Organized Crime / CIA-Mafia ---
    {
        "source": "Carlos Marcello",
        "target": "JFK Assassination",
        "type": "connected_to",
        "tier": "credible",
        "desc": "HSCA found credible evidence of involvement. BRILAB wiretaps captured Marcello: 'Yeah, I had the son of a bitch killed.' Motive: RFK had him deported.",
        "sources": [578, 594],
        "year_start": 1963,
        "year_end": 1963,
    },
    {
        "source": "Santos Trafficante",
        "target": "JFK Assassination",
        "type": "connected_to",
        "tier": "credible",
        "desc": "HSCA found credible evidence of involvement. Participated in CIA-Mafia Castro plots. Lawyer claimed deathbed confession.",
        "sources": [578, 595],
        "year_start": 1963,
        "year_end": 1963,
    },
    {
        "source": "Santos Trafficante",
        "target": "CIA",
        "type": "worked_with",
        "tier": "documented",
        "desc": "CIA recruited Trafficante for Castro assassination plots. Documented by Church Committee and CIA Inspector General report.",
        "sources": [579, 580],
        "year_start": 1960,
        "year_end": 1963,
    },
    {
        "source": "Sam Giancana",
        "target": "CIA",
        "type": "worked_with",
        "tier": "documented",
        "desc": "CIA recruited Giancana for Castro assassination plots through intermediary Robert Maheu. Church Committee documented the arrangement.",
        "sources": [579, 580],
        "year_start": 1960,
        "year_end": 1963,
    },
    {
        "source": "Sam Giancana",
        "target": "JFK Assassination",
        "type": "connected_to",
        "tier": "inference",
        "desc": "Motive (shared mistress with JFK, betrayed by Kennedys after helping 1960 election). Murdered 1975 before Church Committee testimony. Connection is pattern-based.",
        "sources": [596, 579],
        "year_start": 1963,
        "year_end": 1963,
    },
    # --- Dorothy Kilgallen ---
    {
        "source": "Dorothy Kilgallen",
        "target": "JFK Assassination",
        "type": "investigated",
        "tier": "documented",
        "desc": "Only journalist to obtain private interview with Jack Ruby. Told friends she would 'break the case wide open.' Died Nov 1965 — notes never found.",
        "sources": [604],
        "year_start": 1964,
        "year_end": 1965,
    },
    # --- Investigations ---
    {
        "source": "Warren Commission",
        "target": "JFK Assassination",
        "type": "investigated",
        "tier": "documented",
        "desc": "Official investigation. Concluded Oswald acted alone. Report published Sept 1964. Findings challenged by HSCA (1979) which concluded 'probable conspiracy.'",
        "sources": [576],
        "year_start": 1963,
        "year_end": 1964,
    },
    {
        "source": "HSCA",
        "target": "JFK Assassination",
        "type": "investigated",
        "tier": "documented",
        "desc": "Congressional investigation concluded JFK 'probably assassinated as a result of a conspiracy.' Found CIA and FBI deficient in their investigations.",
        "sources": [577, 578],
        "year_start": 1976,
        "year_end": 1979,
    },
    {
        "source": "HSCA",
        "target": "MLK Assassination",
        "type": "investigated",
        "tier": "documented",
        "desc": "Investigated MLK assassination alongside JFK. Found 'likelihood of conspiracy' beyond James Earl Ray.",
        "sources": [607],
        "year_start": 1976,
        "year_end": 1979,
    },
    {
        "source": "ARRB",
        "target": "JFK Assassination",
        "type": "investigated",
        "tier": "documented",
        "desc": "Released millions of classified documents. Found multiple agencies withheld relevant records from Warren Commission.",
        "sources": [581, 582],
        "year_start": 1994,
        "year_end": 1998,
    },
    {
        "source": "J. Edgar Hoover",
        "target": "Warren Commission",
        "type": "connected_to",
        "tier": "documented",
        "desc": "FBI investigation under Hoover was the primary evidence source for Warren Commission. Hoover declared Oswald the lone assassin within hours.",
        "sources": [576, 577],
        "year_start": 1963,
        "year_end": 1964,
    },
    {
        "source": "FBI",
        "target": "Martin Luther King Jr.",
        "type": "monitored",
        "tier": "documented",
        "desc": "COINTELPRO targeted King extensively. Hoover called him 'most dangerous Negro in America.' FBI sent King anonymous letter suggesting suicide.",
        "sources": [607, 608],
        "year_start": 1963,
        "year_end": 1968,
    },
    # --- Programs ---
    {
        "source": "Richard Helms",
        "target": "ZR/RIFLE",
        "type": "authorized",
        "tier": "documented",
        "desc": "As CIA Deputy Director of Plans, authorized William Harvey to run ZR/RIFLE assassination program. Documented by Church Committee.",
        "sources": [579, 601],
        "year_start": 1961,
        "year_end": 1963,
    },
    {
        "source": "Church Committee",
        "target": "ZR/RIFLE",
        "type": "exposed",
        "tier": "documented",
        "desc": "Church Committee revealed the existence of ZR/RIFLE and CIA assassination capabilities in 1975 report.",
        "sources": [579, 601],
        "year_start": 1975,
        "year_end": 1975,
    },
    {
        "source": "Church Committee",
        "target": "Operation Mongoose",
        "type": "exposed",
        "tier": "documented",
        "desc": "Church Committee documented Operation Mongoose and the CIA-Mafia assassination plots it encompassed.",
        "sources": [579, 600],
        "year_start": 1975,
        "year_end": 1975,
    },
    # --- RFK / MLK ---
    {
        "source": "Robert F. Kennedy",
        "target": "RFK Assassination",
        "type": "connected_to",
        "tier": "documented",
        "desc": "Assassinated June 5, 1968 during presidential campaign. Autopsy showed fatal shot from behind at contact range — Sirhan was in front.",
        "sources": [605, 606],
        "year_start": 1968,
        "year_end": 1968,
    },
    {
        "source": "Sirhan Sirhan",
        "target": "RFK Assassination",
        "type": "participated_in",
        "tier": "documented",
        "desc": "Convicted of assassination. In trance-like state. Gun held 8 rounds but witnesses/audio suggest 13+ shots. Autopsy inconsistent with his firing position.",
        "sources": [605, 606],
        "year_start": 1968,
        "year_end": 1968,
    },
    {
        "source": "Martin Luther King Jr.",
        "target": "MLK Assassination",
        "type": "connected_to",
        "tier": "documented",
        "desc": "Assassinated April 4, 1968. 1999 civil trial jury found government agencies participated in assassination plot.",
        "sources": [607, 608],
        "year_start": 1968,
        "year_end": 1968,
    },
    {
        "source": "James Earl Ray",
        "target": "MLK Assassination",
        "type": "participated_in",
        "tier": "documented",
        "desc": "Pleaded guilty, recanted within days. Escaped convict with international travel (suggesting support network). King family believed he was a patsy.",
        "sources": [607, 608],
        "year_start": 1968,
        "year_end": 1968,
    },
    # --- Vietnam Policy Context ---
    {
        "source": "Allen Dulles",
        "target": "MKULTRA",
        "type": "authorized",
        "tier": "documented",
        "desc": "As CIA Director, authorized MKULTRA mind control program in 1953.",
        "sources": [585, 609],
        "year_start": 1953,
        "year_end": 1961,
    },
]

# ============================================================
# ENTITY_SOURCES — links entities to their key sources
# ============================================================

ENTITY_SOURCES = {
    "Allen Dulles": [585, 609, 576],
    "John McCone": [576, 581],
    "David Atlee Phillips": [603, 588],
    "E. Howard Hunt": [589],
    "Lee Harvey Oswald": [576, 577, 588, 592, 614],
    "Jack Ruby": [576, 578, 597],
    "Clay Shaw": [583, 590, 591],
    "David Ferrie": [583, 611],
    "Guy Banister": [610, 577],
    "Jim Garrison": [583, 590],
    "George de Mohrenschildt": [593, 577],
    "Carlos Marcello": [578, 594],
    "Santos Trafficante": [578, 579, 595],
    "Sam Giancana": [579, 580, 596],
    "Dorothy Kilgallen": [604],
    "Warren Commission": [576],
    "HSCA": [577, 578, 607],
    "ARRB": [581, 582],
    "Operation Mongoose": [579, 600],
    "ZR/RIFLE": [579, 601],
    "Operation 40": [602],
    "Dealey Plaza": [576, 612],
    "JFK Assassination": [576, 577, 581, 584, 587, 614],
    "Robert F. Kennedy": [605, 606],
    "RFK Assassination": [605, 606],
    "Sirhan Sirhan": [605, 606],
    "Martin Luther King Jr.": [607, 608],
    "MLK Assassination": [607, 608],
    "James Earl Ray": [607, 608],
}
