"""
Disclosure Scrolls — Entity expansion for Intel Console.

Entities referenced in the Disclosure Scrolls (disclosure-scrolls.netlify.app)
that were not already present in the Intel Console. These are persons,
organizations, programs, facilities, and events mentioned across the 11-scroll
documentary series.

Evidence tiers:
  documented = congressional record, court filing, FOIA, official government doc
  credible   = quality investigative journalism, on-record testimony, academic research
  inference  = pattern-based conclusion from documented facts
  speculative = theory requiring further evidence
"""

# Source IDs start at 1415
SOURCES = [
    {"id": 1415, "title": "The Flexner Report (1910)", "url": "https://archive.org/details/flexnerreport00markup", "source_type": "academic", "author": "Abraham Flexner", "year": 1910},
    {"id": 1416, "title": "The Father of Spin: Edward L. Bernays and the Birth of Public Relations", "url": "", "source_type": "book", "author": "Larry Tye", "year": 1998},
    {"id": 1417, "title": "Propaganda (1928)", "url": "https://archive.org/details/propaganda00bern", "source_type": "book", "author": "Edward Bernays", "year": 1928},
    {"id": 1418, "title": "The Sugar Industry and Coronary Heart Disease Research (JAMA Internal Medicine)", "url": "https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/2548255", "source_type": "academic", "author": "Cristin Kearns, Laura Schmidt, Stanton Glantz", "year": 2016},
    {"id": 1419, "title": "Church Committee Final Report Vol. 1 (1976)", "url": "https://www.intelligence.senate.gov/publications/final-report-select-committee-study-governmental-operations-respect-intelligence", "source_type": "congressional", "author": "Senate Select Committee", "year": 1976},
    {"id": 1420, "title": "Tragedy and Hope (1966)", "url": "", "source_type": "book", "author": "Carroll Quigley", "year": 1966},
    {"id": 1421, "title": "Bob Lazar: Area 51 & Flying Saucers (Documentary)", "url": "", "source_type": "documentary", "author": "Jeremy Corbell", "year": 2018},
    {"id": 1422, "title": "The Day After Roswell (1997)", "url": "", "source_type": "book", "author": "Philip Corso", "year": 1997},
    {"id": 1423, "title": "Canadian Defence Minister Paul Hellyer UAP Testimony", "url": "", "source_type": "other", "author": "Paul Hellyer", "year": 2013},
    {"id": 1424, "title": "Acid Dreams: The Complete Social History of LSD", "url": "", "source_type": "book", "author": "Martin Lee, Bruce Shlain", "year": 1985},
    {"id": 1425, "title": "HAARP Official Fact Sheet", "url": "https://haarp.gi.alaska.edu/", "source_type": "government", "author": "University of Alaska Fairbanks", "year": 2015},
    {"id": 1426, "title": "Angels Don't Play This HAARP", "url": "", "source_type": "book", "author": "Nick Begich, Jeane Manning", "year": 1995},
    {"id": 1427, "title": "Eastlund HAARP Patent US4686605A", "url": "https://patents.google.com/patent/US4686605A", "source_type": "government", "author": "Bernard Eastlund", "year": 1987},
    {"id": 1428, "title": "Christopher Mellon UAP Congressional Testimony", "url": "", "source_type": "congressional", "author": "Christopher Mellon", "year": 2022},
    {"id": 1429, "title": "Karen Silkwood Case: Kerr-McGee v. Silkwood (1979)", "url": "", "source_type": "court", "author": "US Supreme Court", "year": 1979},
    {"id": 1430, "title": "Geoengineering: Governance and Technology Policy (Congressional Research Service)", "url": "https://crsreports.congress.gov/product/pdf/R/R41371", "source_type": "congressional", "author": "Congressional Research Service", "year": 2013},
    {"id": 1431, "title": "The Aquarian Conspiracy (1980)", "url": "", "source_type": "book", "author": "Marilyn Ferguson", "year": 1980},
    {"id": 1432, "title": "The Confessions of an Economic Hit Man", "url": "", "source_type": "book", "author": "John Perkins", "year": 2004},
    {"id": 1433, "title": "The Case Against Fluoride", "url": "", "source_type": "book", "author": "Paul Connett, James Beck, H. S. Micklem", "year": 2010},
    {"id": 1434, "title": "Enrico Mattei Assassination Investigation", "url": "", "source_type": "journalism", "author": "Various Italian journalists", "year": 1962},
    {"id": 1435, "title": "Wilhelm Reich FDA Injunction and Imprisonment", "url": "", "source_type": "court", "author": "US District Court", "year": 1954},
    {"id": 1436, "title": "Cecil Rhodes: Last Will and Testament", "url": "https://archive.org/details/lastwilltestame00rhod", "source_type": "archive", "author": "Cecil Rhodes", "year": 1902},
    {"id": 1437, "title": "The Mark Lombardi Global Networks Exhibition", "url": "", "source_type": "other", "author": "Whitney Museum of American Art", "year": 2003},
    {"id": 1438, "title": "Silkwood (film) and Karen Silkwood Investigation", "url": "", "source_type": "journalism", "author": "The New York Times", "year": 1974},
    {"id": 1439, "title": "Dario Amodei Testimony Before Senate (2023)", "url": "", "source_type": "congressional", "author": "Senate Judiciary Committee", "year": 2023},
    {"id": 1440, "title": "SCoPEx: Stratospheric Controlled Perturbation Experiment", "url": "", "source_type": "academic", "author": "Harvard Solar Geoengineering Research Program", "year": 2019},
    {"id": 1441, "title": "Operation Popeye Weather Modification Senate Hearing (1974)", "url": "", "source_type": "congressional", "author": "Senate Foreign Relations Committee", "year": 1974},
    {"id": 1442, "title": "Sam Altman OpenAI Leadership", "url": "", "source_type": "journalism", "author": "Various", "year": 2023},
    {"id": 1443, "title": "The Stargate Conspiracy (1999)", "url": "", "source_type": "book", "author": "Lynn Picknett, Clive Prince", "year": 1999},
    {"id": 1444, "title": "Lucis Trust UN Consultative Status Records", "url": "https://www.lucistrust.org/", "source_type": "other", "author": "Lucis Trust", "year": 1922},
    {"id": 1445, "title": "Esalen Institute History", "url": "https://www.esalen.org/", "source_type": "other", "author": "Esalen Institute", "year": 1962},
    {"id": 1446, "title": "The Electric Kool-Aid Acid Test (1968)", "url": "", "source_type": "book", "author": "Tom Wolfe", "year": 1968},
    {"id": 1447, "title": "Turn On, Tune In, Drop Out (1966)", "url": "", "source_type": "book", "author": "Timothy Leary", "year": 1966},
    {"id": 1448, "title": "US Space Force Established (2019)", "url": "", "source_type": "government", "author": "US Government", "year": 2019},
    {"id": 1449, "title": "National Reconnaissance Office Declassification", "url": "", "source_type": "government", "author": "NRO", "year": 1992},
    {"id": 1450, "title": "Prince Bernhard and Bilderberg Founding", "url": "", "source_type": "journalism", "author": "Various", "year": 1954},
    {"id": 1451, "title": "John Foster Dulles and US Cold War Policy", "url": "", "source_type": "academic", "author": "Various historians", "year": 1954},
    {"id": 1452, "title": "William Colby CIA Directorship and Death", "url": "", "source_type": "journalism", "author": "Washington Post", "year": 1996},
    {"id": 1453, "title": "James Woolsey CIA Tenure", "url": "", "source_type": "government", "author": "CIA Historical Review Program", "year": 1993},
    {"id": 1454, "title": "Leon Panetta CIA/DoD Tenure", "url": "", "source_type": "government", "author": "CIA", "year": 2009},
    {"id": 1455, "title": "John Brennan CIA Directorship", "url": "", "source_type": "government", "author": "CIA", "year": 2013},
    {"id": 1456, "title": "Michael Hayden NSA/CIA Directorships", "url": "", "source_type": "government", "author": "NSA/CIA", "year": 2006},
    {"id": 1457, "title": "David Petraeus CIA Tenure and Scandal", "url": "", "source_type": "journalism", "author": "Various", "year": 2012},
    {"id": 1458, "title": "John Kerry Senate Foreign Relations Committee", "url": "", "source_type": "congressional", "author": "US Senate", "year": 2009},
    {"id": 1459, "title": "James Clapper DNI Tenure", "url": "", "source_type": "government", "author": "ODNI", "year": 2010},
    {"id": 1460, "title": "Make Sunsets Unauthorized SAI Launches", "url": "", "source_type": "journalism", "author": "MIT Technology Review", "year": 2022},
    {"id": 1461, "title": "Nag Hammadi Library Discovery and Translation", "url": "", "source_type": "academic", "author": "James M. Robinson", "year": 1945},
    {"id": 1462, "title": "Dead Sea Scrolls Discovery and Publication", "url": "", "source_type": "academic", "author": "Various", "year": 1947},
    {"id": 1463, "title": "OpenAI Charter and Corporate Structure", "url": "https://openai.com/charter/", "source_type": "other", "author": "OpenAI", "year": 2018},
    {"id": 1464, "title": "Meta/Facebook Corporate Filings", "url": "", "source_type": "other", "author": "Meta Platforms Inc.", "year": 2021},
    {"id": 1465, "title": "Anthropic AI Safety Research", "url": "https://www.anthropic.com/", "source_type": "other", "author": "Anthropic", "year": 2021},
]

ENTITIES = [
    # ── PERSONS ──────────────────────────────────────────────────
    {
        "name": "Dario Amodei",
        "entity_type": "person",
        "description": "CEO and co-founder of Anthropic. Former VP of Research at OpenAI. Key figure in AI safety movement. Testified before US Senate on AI risks (2023). Refused Pentagon demands for military AI integration as depicted in Disclosure Scrolls AI Wars.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Sam Altman",
        "entity_type": "person",
        "description": "CEO of OpenAI. Previously president of Y Combinator. Central figure in AI commercialization and the race to AGI. Briefly ousted by OpenAI board in November 2023 before being reinstated. Struck Pentagon AI deals while publicly criticizing competitors.",
        "aliases": "Samuel Altman",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Mark Zuckerberg",
        "entity_type": "person",
        "description": "CEO of Meta Platforms (formerly Facebook). Built world's largest social network. Faced congressional hearings over Cambridge Analytica data harvesting, election interference, and content moderation failures. LifeLog (DARPA) was cancelled the same day Facebook launched.",
        "aliases": "Zuck",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Sean Parker",
        "entity_type": "person",
        "description": "First president of Facebook. Co-founder of Napster. Early tech industry disruptor. Publicly admitted Facebook was designed to exploit human psychology: 'God only knows what it's doing to our children's brains.'",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Abraham Flexner",
        "entity_type": "person",
        "description": "Author of the Flexner Report (1910), funded by the Carnegie Foundation. The report led to the closure of nearly half of American medical schools, consolidating medical education under AMA/Rockefeller Foundation control and marginalizing alternative medicine.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Morris Fishbein",
        "entity_type": "person",
        "description": "Editor of the Journal of the American Medical Association (JAMA) from 1924-1950. Used his position to suppress alternative medical treatments and practitioners including Royal Raymond Rife and Harry Hoxsey. Key enforcer of AMA orthodoxy.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Ancel Keys",
        "entity_type": "person",
        "description": "Physiologist behind the Seven Countries Study that blamed dietary fat for heart disease. His lipid hypothesis shaped US dietary guidelines for decades. Later research revealed the sugar industry funded studies to shift blame from sugar to fat.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "John Yudkin",
        "entity_type": "person",
        "description": "British physiologist who identified sugar as a primary cause of heart disease in 'Pure, White and Deadly' (1972). His work was systematically discredited by the sugar industry and Ancel Keys. Later vindicated by modern research.",
        "aliases": "",
        "metadata": {"nationality": "British", "status": "deceased"},
    },
    {
        "name": "Max Gerson",
        "entity_type": "person",
        "description": "German-American physician who developed the Gerson Therapy for cancer treatment using nutrition and detoxification. Testified before US Senate (1946). His work was suppressed by the AMA. Died under suspicious circumstances in 1959.",
        "aliases": "",
        "metadata": {"nationality": "German-American", "status": "deceased"},
    },
    {
        "name": "Harry Hoxsey",
        "entity_type": "person",
        "description": "Alternative cancer treatment practitioner who operated clinics across the US in the 1950s. Engaged in a decades-long legal battle with Morris Fishbein and the AMA. FDA shut down his clinics. His formula is still used at a clinic in Tijuana, Mexico.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Wilhelm Reich",
        "entity_type": "person",
        "description": "Austrian psychoanalyst and inventor of orgone energy theory. Developed the orgone accumulator and cloudbuster devices. FDA obtained an injunction against his work in 1954. His books were burned by the US government. Died in federal prison in 1957.",
        "aliases": "",
        "metadata": {"nationality": "Austrian-American", "status": "deceased"},
    },
    {
        "name": "Richard Sackler",
        "entity_type": "person",
        "description": "Former president of Purdue Pharma and member of the Sackler family. Key architect of OxyContin's aggressive marketing strategy that fueled the US opioid epidemic. Shielded by family bankruptcy deal that dissolved Purdue Pharma.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Cristin Kearns",
        "entity_type": "person",
        "description": "Dentist-turned-researcher at UCSF who uncovered sugar industry documents showing the Sugar Research Foundation paid Harvard scientists to shift blame for heart disease from sugar to fat. Her 2016 JAMA Internal Medicine paper exposed decades of scientific corruption.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Walter Lippmann",
        "entity_type": "person",
        "description": "Influential American journalist and political commentator. Author of 'Public Opinion' (1922), which theorized the 'manufacture of consent' — the idea that public opinion could and should be shaped by elite media managers. Founding member of CFR.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Carroll Quigley",
        "entity_type": "person",
        "description": "Georgetown University professor and historian. Author of 'Tragedy and Hope' (1966), which documented the existence of an Anglo-American power network seeking global governance. Mentor to Bill Clinton. His work is a primary source for understanding supranational elite coordination.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Cecil Rhodes",
        "entity_type": "person",
        "description": "British mining magnate, politician, and founder of Rhodesia. His last will established the Rhodes Scholarship and outlined a plan for a secret society to extend British influence globally. His vision influenced the founding of the Round Table movement and subsequent supranational organizations.",
        "aliases": "",
        "metadata": {"nationality": "British", "status": "deceased"},
    },
    {
        "name": "Prince Bernhard",
        "entity_type": "person",
        "description": "Prince Consort of the Netherlands. Former member of the Nazi Party and IG Farben employee. Co-founder of the Bilderberg Group (1954) alongside Polish political advisor Józef Retinger. Chairman of Bilderberg until the Lockheed bribery scandal forced his resignation in 1976.",
        "aliases": "Prince Bernhard of the Netherlands, Bernhard of Lippe-Biesterfeld",
        "metadata": {"nationality": "Dutch-German", "status": "deceased"},
    },
    {
        "name": "John Foster Dulles",
        "entity_type": "person",
        "description": "US Secretary of State (1953-1959) under Eisenhower. Brother of CIA Director Allen Dulles. Senior partner at Sullivan & Cromwell, which represented IG Farben and other German industrial interests before WWII. Key architect of Cold War containment and rollback doctrine.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "William Colby",
        "entity_type": "person",
        "description": "CIA Director (1973-1976). Oversaw Operation Phoenix in Vietnam. Revealed CIA abuses to the Church Committee, earning enmity within the intelligence community. Found dead in 1996 under circumstances many consider suspicious — drowned while canoeing near his Maryland home.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "James Woolsey",
        "entity_type": "person",
        "description": "CIA Director (1993-1995) under Bill Clinton. Later became a prominent advocate for the Iraq War and neoconservative foreign policy. Connected to the Project for the New American Century (PNAC). Served on boards of defense and intelligence contractors.",
        "aliases": "R. James Woolsey",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Leon Panetta",
        "entity_type": "person",
        "description": "CIA Director (2009-2011) and Secretary of Defense (2011-2013) under Obama. Previously White House Chief of Staff under Clinton. Oversaw the CIA during the Bin Laden raid. Career spanning Congress, OMB, and national security leadership.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "John Brennan",
        "entity_type": "person",
        "description": "CIA Director (2013-2017) under Obama. Former CIA station chief in Saudi Arabia. Homeland Security Advisor. Oversaw expansion of drone strike program. Post-CIA, became vocal Trump critic. Controversial figure in Russiagate investigation.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Michael Hayden",
        "entity_type": "person",
        "description": "NSA Director (1999-2005) and CIA Director (2006-2009). Oversaw creation of warrantless surveillance programs including STELLARWIND after 9/11. First person to lead both NSA and CIA. Key figure in post-9/11 surveillance state expansion.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "David Petraeus",
        "entity_type": "person",
        "description": "CIA Director (2011-2012). Former four-star general who commanded forces in Iraq and Afghanistan. Architect of the Iraq 'surge' strategy. Resigned from CIA after affair and classified information leak. Later joined KKR as partner.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "James Clapper",
        "entity_type": "person",
        "description": "Director of National Intelligence (2010-2017). Infamously told Congress the NSA does not 'wittingly' collect data on Americans — later proven false by Snowden revelations. Oversaw all 17 US intelligence agencies during peak surveillance expansion.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "John Kerry",
        "entity_type": "person",
        "description": "US Senator, Secretary of State (2013-2017), and Presidential Climate Envoy. Member of Skull and Bones. Led the Kerry Committee investigation (1989) that exposed CIA-Contra drug trafficking connections. Later served as chief Iran nuclear deal negotiator.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Bob Lazar",
        "entity_type": "person",
        "description": "Claimed to have worked on reverse-engineering extraterrestrial technology at S-4 facility near Area 51 in the late 1980s. His 1989 public disclosure introduced Area 51 to mainstream awareness. His claims remain unverified but have influenced UAP discourse for decades.",
        "aliases": "Robert Lazar",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Christopher Mellon",
        "entity_type": "person",
        "description": "Former Deputy Assistant Secretary of Defense for Intelligence. Key figure in UAP disclosure alongside Luis Elizondo. Helped leak Navy UAP videos to the New York Times (2017). Testified before Congress on UAP. Son of banking dynasty (Mellon family).",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Paul Hellyer",
        "entity_type": "person",
        "description": "Canadian Minister of National Defence (1963-1967). Highest-ranking government official to publicly declare that UFOs are real and that governments have been concealing extraterrestrial contact. Made his public UAP testimony in 2005.",
        "aliases": "",
        "metadata": {"nationality": "Canadian", "status": "deceased"},
    },
    {
        "name": "Philip Corso",
        "entity_type": "person",
        "description": "US Army Lt. Colonel who served on Eisenhower's National Security Council. Author of 'The Day After Roswell' (1997), claiming he seeded recovered alien technology into private industry through Army R&D channels. His claims remain controversial.",
        "aliases": "Philip J. Corso",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Gordon Cooper",
        "entity_type": "person",
        "description": "NASA Mercury and Gemini astronaut. One of the original Mercury Seven. Publicly testified about UFO encounters during his military career and called for government transparency on the subject. His testimony lends credibility to disclosure efforts.",
        "aliases": "Leroy Gordon Cooper Jr.",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Karl Wolfe",
        "entity_type": "person",
        "description": "US Air Force Sergeant who testified at the National Press Club (2001 Disclosure Project) that he saw photographs of structures on the far side of the Moon while stationed at NSA's Tactical Air Command facility at Langley AFB in 1965.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Timothy Leary",
        "entity_type": "person",
        "description": "Harvard psychologist and counterculture icon. Pioneer of psychedelic research with psilocybin and LSD. Fired from Harvard in 1963. His 'Turn on, tune in, drop out' slogan defined 1960s counterculture. Connections to CIA through MKUltra-adjacent research programs.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Ken Kesey",
        "entity_type": "person",
        "description": "Author of 'One Flew Over the Cuckoo's Nest'. Participated in MKUltra LSD experiments at Menlo Park VA Hospital as a volunteer. Went on to lead the Merry Pranksters and popularize LSD, directly bridging CIA drug experimentation and 1960s counterculture.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Aldous Huxley",
        "entity_type": "person",
        "description": "British author of 'Brave New World' (1932) and 'The Doors of Perception' (1954). Pioneered Western psychedelic experimentation. Connected to British intelligence circles through his family (brother Julian Huxley headed UNESCO). Died November 22, 1963 — same day as JFK.",
        "aliases": "",
        "metadata": {"nationality": "British", "status": "deceased"},
    },
    {
        "name": "R. Gordon Wasson",
        "entity_type": "person",
        "description": "VP of J.P. Morgan and amateur mycologist. Published the first mainstream account of psilocybin mushroom use in Life Magazine (1957). His expedition to Mexico was partially funded by CIA through MKUltra subprojects. Bridge between Wall Street, intelligence, and psychedelics.",
        "aliases": "Robert Gordon Wasson",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Helena Blavatsky",
        "entity_type": "person",
        "description": "Founder of the Theosophical Society (1875). Author of 'The Secret Doctrine' and 'Isis Unveiled'. Her esoteric philosophy influenced both New Age movements and early 20th-century occult organizations. Her work on 'root races' was later co-opted by Nazi mystics.",
        "aliases": "Madame Blavatsky, HPB",
        "metadata": {"nationality": "Russian", "status": "deceased"},
    },
    {
        "name": "Alice Bailey",
        "entity_type": "person",
        "description": "Theosophist and author who founded the Lucis Trust (originally Lucifer Publishing Company) in 1922. Her writings on a 'New World Order' and global governance through spiritual evolution heavily influenced UN-affiliated organizations and New Age movement leadership.",
        "aliases": "",
        "metadata": {"nationality": "British-American", "status": "deceased"},
    },
    {
        "name": "Marilyn Ferguson",
        "entity_type": "person",
        "description": "Author of 'The Aquarian Conspiracy' (1980), which became a manifesto for the New Age movement. The book documented a 'leaderless but powerful network' working to transform society through personal and social transformation. Connected to SRI and consciousness research circles.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Willis Harman",
        "entity_type": "person",
        "description": "President of the Institute of Noetic Sciences and senior social scientist at SRI International. Directed the 'Changing Images of Man' study at Stanford. Key figure connecting consciousness research, military intelligence, and the human potential movement.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Robert Muller",
        "entity_type": "person",
        "description": "Former UN Assistant Secretary-General. Served at the United Nations for 40 years. Developed the 'World Core Curriculum' for global education based on Alice Bailey's teachings. His vision of world government through spiritual transformation influenced UN policy frameworks.",
        "aliases": "",
        "metadata": {"nationality": "French-American", "status": "deceased"},
    },
    {
        "name": "Jim Morrison",
        "entity_type": "person",
        "description": "Lead singer of The Doors. Son of Admiral George S. Morrison, who commanded the fleet during the Gulf of Tonkin incident. His military intelligence family background and proximity to Laurel Canyon's music scene connects to broader questions about counterculture origins.",
        "aliases": "James Douglas Morrison",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Frank Zappa",
        "entity_type": "person",
        "description": "Musician, composer, and Laurel Canyon scene figure. Son of Francis Zappa, a chemical warfare specialist at Edgewood Arsenal. Grew up on military bases. His family's military-intelligence background is part of the broader Laurel Canyon military family pattern documented by David McGowan.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Richard Doty",
        "entity_type": "person",
        "description": "Former AFOSI (Air Force Office of Special Investigations) special agent. Admitted to running disinformation campaigns against UFO researchers, particularly Paul Bennewitz. Key figure in understanding how military counterintelligence manipulates the UFO community.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Paul Bennewitz",
        "entity_type": "person",
        "description": "Physicist and businessman who detected unusual signals near Kirtland AFB. Became a target of AFOSI disinformation operations led by Richard Doty. Was fed false information about alien bases until he suffered a mental breakdown. A cautionary tale of intelligence manipulation.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Enrico Mattei",
        "entity_type": "person",
        "description": "Head of Italian state oil company ENI. Challenged the Seven Sisters oil cartel by making independent deals with oil-producing nations. Died in a suspicious plane crash in 1962. Italian courts later ruled the crash was sabotage, likely involving CIA and French intelligence.",
        "aliases": "",
        "metadata": {"nationality": "Italian", "status": "deceased"},
    },
    {
        "name": "Ida Tarbell",
        "entity_type": "person",
        "description": "Pioneering investigative journalist whose 'The History of the Standard Oil Company' (1904) exposed John D. Rockefeller's monopolistic practices. Her work led to the Supreme Court's breakup of Standard Oil in 1911. One of the original American muckrakers.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Henri Deterding",
        "entity_type": "person",
        "description": "Dutch businessman who led Royal Dutch Shell and was one of the most powerful figures in the early oil industry. Known as the 'Napoleon of Oil.' Became a Nazi sympathizer in the 1930s. His rivalry with Standard Oil shaped the global energy landscape.",
        "aliases": "",
        "metadata": {"nationality": "Dutch", "status": "deceased"},
    },
    {
        "name": "Fritz ter Meer",
        "entity_type": "person",
        "description": "IG Farben board member convicted at the Nuremberg trials for war crimes related to the use of slave labor and poison gas. Sentenced to 7 years, released early. Later became chairman of Bayer AG's supervisory board, exemplifying Operation Paperclip-era rehabilitation of Nazi industrialists.",
        "aliases": "",
        "metadata": {"nationality": "German", "status": "deceased"},
    },
    {
        "name": "Kermit Roosevelt Jr.",
        "entity_type": "person",
        "description": "CIA officer who led Operation Ajax (1953), the coup that overthrew Iranian PM Mohammad Mossadegh. Grandson of President Theodore Roosevelt. His success in Iran established the template for CIA regime change operations worldwide.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "John Perkins",
        "entity_type": "person",
        "description": "Author of 'Confessions of an Economic Hit Man' (2004). Claims to have worked as an economic consultant whose real job was to saddle developing nations with unpayable debt to benefit US corporate interests. His account describes the modern mechanism of economic imperialism.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Muammar Gaddafi",
        "entity_type": "person",
        "description": "Libyan leader (1969-2011). Nationalized Libya's oil. Proposed a gold-backed African currency (the Gold Dinar) that threatened petrodollar hegemony. Overthrown and killed in NATO-backed intervention in 2011. Libya descended into failed-state chaos.",
        "aliases": "Muammar al-Gaddafi, Gaddafi, Qaddafi",
        "metadata": {"nationality": "Libyan", "status": "deceased"},
    },
    {
        "name": "Hugo Chávez",
        "entity_type": "person",
        "description": "President of Venezuela (1999-2013). Nationalized the oil industry and challenged US hegemony in Latin America. Survived a US-backed coup attempt in 2002. Used oil revenues to fund social programs. Died of cancer in 2013 under circumstances he himself suggested were suspicious.",
        "aliases": "Hugo Rafael Chávez Frías",
        "metadata": {"nationality": "Venezuelan", "status": "deceased"},
    },
    {
        "name": "Nicolas Sarkozy",
        "entity_type": "person",
        "description": "President of France (2007-2012). Led the NATO intervention in Libya. Reportedly received illegal campaign financing from Gaddafi's Libya — later charged. Key figure in the destruction of the Libyan state and the Gold Dinar plan.",
        "aliases": "",
        "metadata": {"nationality": "French", "status": "alive"},
    },
    {
        "name": "Bernard J. Eastlund",
        "entity_type": "person",
        "description": "Physicist who held the key patent (US4686605A) underlying HAARP technology. His patent described using high-power radio frequency energy to modify the ionosphere. The patent was initially classified by the US military before being made public.",
        "aliases": "Bernard Eastlund",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Alan Robock",
        "entity_type": "person",
        "description": "Rutgers University climate scientist and leading researcher on volcanic winters and nuclear winter. Critic of solar geoengineering proposals. Has documented 27 reasons why stratospheric aerosol injection is a bad idea. Key voice in geoengineering governance debates.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "David Keith",
        "entity_type": "person",
        "description": "Harvard professor and leading proponent of solar geoengineering research. Founded the Harvard Solar Geoengineering Research Program and the SCoPEx experiment. Also co-founded Carbon Engineering. Central figure in the academic push for climate intervention research.",
        "aliases": "",
        "metadata": {"nationality": "Canadian", "status": "alive"},
    },
    {
        "name": "Frank Keutsch",
        "entity_type": "person",
        "description": "Harvard atmospheric chemist and principal investigator of the SCoPEx (Stratospheric Controlled Perturbation Experiment) project. SCoPEx aimed to test aerosol injection at small scale but was halted after public opposition, particularly from indigenous groups in Sweden.",
        "aliases": "",
        "metadata": {"nationality": "German-American", "status": "alive"},
    },
    {
        "name": "Ken Caldeira",
        "entity_type": "person",
        "description": "Climate scientist at the Carnegie Institution for Science (now at Breakthrough Energy). Early modeler of solar geoengineering effects. His research showed aerosol injection could reduce global temperatures but with significant regional side effects.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Luke Iseman",
        "entity_type": "person",
        "description": "CEO of Make Sunsets, the controversial startup that launched unauthorized stratospheric aerosol injection balloons releasing sulfur dioxide particles in 2022. The launches were conducted without regulatory approval, sparking international condemnation and reigniting geoengineering governance debates.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Mark Lombardi",
        "entity_type": "person",
        "description": "Artist who created intricate hand-drawn network diagrams mapping connections between governments, financial institutions, and criminal enterprises. His work visualized BCCI, Iran-Contra, and other conspiracies. Died by hanging in 2000 — ruled suicide, widely questioned. FBI visited his studio after his death to photograph his work.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Karen Silkwood",
        "entity_type": "person",
        "description": "Chemical technician at the Kerr-McGee plutonium processing plant in Oklahoma. Discovered safety violations and plutonium contamination. Died in a suspicious car crash in 1974 while en route to deliver documents to a NYT reporter. Her case became a landmark nuclear safety story.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Neil Armstrong",
        "entity_type": "person",
        "description": "NASA astronaut, first human to walk on the Moon (Apollo 11, July 20, 1969). Naval aviator and test pilot. His post-Apollo reclusiveness and cryptic public statements about 'truth's protective layers' have fueled speculation about what was found on the lunar surface.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "deceased"},
    },
    {
        "name": "Buzz Aldrin",
        "entity_type": "person",
        "description": "NASA astronaut, second human to walk on the Moon (Apollo 11). Fighter pilot in Korean War (66 combat missions). Later became a vocal advocate for Mars colonization. His accounts of a UAP sighting during the Apollo 11 transit have been debated for decades.",
        "aliases": "Edwin Eugene Aldrin Jr.",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Joel Osteen",
        "entity_type": "person",
        "description": "Pastor of Lakewood Church in Houston, the largest megachurch in the United States. Represents the prosperity gospel movement — the theological framework that equates wealth with divine blessing. His estimated net worth exceeds $100 million.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    {
        "name": "Kenneth Copeland",
        "entity_type": "person",
        "description": "Televangelist and prosperity gospel preacher. Estimated net worth over $300 million. Owns multiple private jets. His ministry exemplifies the financial extraction model of modern megachurch televangelism. Has faced scrutiny from Senate investigations into nonprofit abuse.",
        "aliases": "",
        "metadata": {"nationality": "American", "status": "alive"},
    },
    # ── ORGANIZATIONS ────────────────────────────────────────────
    {
        "name": "OpenAI",
        "entity_type": "organization",
        "description": "AI research company founded in 2015 as a nonprofit, later restructured as a capped-profit entity. Creator of GPT series and ChatGPT. Key players include Sam Altman (CEO) and former members who left to found Anthropic. Struck Pentagon AI deals.",
        "aliases": "",
        "metadata": {},
    },
    {
        "name": "Meta",
        "entity_type": "organization",
        "description": "Parent company of Facebook, Instagram, and WhatsApp (renamed from Facebook in 2021). Founded by Mark Zuckerberg. The world's largest social network. Facebook launched on the same day DARPA cancelled LifeLog — a program with an almost identical data-collection mission.",
        "aliases": "Meta Platforms, Facebook",
        "metadata": {},
    },
    {
        "name": "Anthropic",
        "entity_type": "organization",
        "description": "AI safety company founded in 2021 by former OpenAI researchers Dario and Daniela Amodei. Creator of Claude AI. Focused on AI alignment research. Subject of national security designation in 2026 as depicted in Disclosure Scrolls AI Wars.",
        "aliases": "",
        "metadata": {},
    },
    {
        "name": "Lucis Trust",
        "entity_type": "organization",
        "description": "Originally incorporated as Lucifer Publishing Company in 1922 by Alice Bailey. Now operates as a UN-accredited NGO with consultative status. Publishes esoteric/Theosophical literature. Maintains the Arcane School and World Goodwill initiative. Connected to UN spiritual governance networks.",
        "aliases": "Lucifer Publishing Company",
        "metadata": {},
    },
    {
        "name": "Esalen Institute",
        "entity_type": "organization",
        "description": "Human potential movement center founded in 1962 in Big Sur, California. Hosted pioneering workshops on consciousness, psychedelics, and Eastern philosophy. Also served as meeting ground between CIA researchers, Soviet scientists, and New Age thought leaders during Cold War.",
        "aliases": "Esalen",
        "metadata": {},
    },
    {
        "name": "Make Sunsets",
        "entity_type": "organization",
        "description": "Startup founded by Luke Iseman that launched unauthorized stratospheric aerosol injection experiments in 2022, releasing sulfur dioxide via weather balloons. Sells 'cooling credits.' Banned by Mexico's government. Represents the rogue geoengineering threat.",
        "aliases": "",
        "metadata": {},
    },
    {
        "name": "Sandoz Labs",
        "entity_type": "organization",
        "description": "Swiss pharmaceutical company where Albert Hofmann first synthesized LSD in 1938. Supplied LSD to the CIA for MKUltra experiments. Later merged with Ciba-Geigy to form Novartis. The original source of the substance that reshaped both intelligence operations and counterculture.",
        "aliases": "Sandoz Laboratories, Sandoz",
        "metadata": {},
    },
    {
        "name": "Hughes Aircraft",
        "entity_type": "organization",
        "description": "Aerospace and defense company founded by Howard Hughes. Major defense contractor involved in satellite, radar, and weapons systems. Its atmospheric research patents are connected to weather modification technology. Acquired by Raytheon in 1997.",
        "aliases": "Hughes Aircraft Company",
        "metadata": {},
    },
    {
        "name": "Stardust Solutions",
        "entity_type": "organization",
        "description": "Cloud-seeding company involved in weather modification operations. Part of the growing commercial weather modification industry that operates with limited public oversight or regulatory framework.",
        "aliases": "",
        "metadata": {},
    },
    # ── AGENCIES ─────────────────────────────────────────────────
    {
        "name": "AFOSI",
        "entity_type": "agency",
        "description": "Air Force Office of Special Investigations. The US Air Force's federal law enforcement and counterintelligence agency. Conducted disinformation operations against UFO researchers including Paul Bennewitz through agents like Richard Doty.",
        "aliases": "Air Force Office of Special Investigations, Air Force OSI",
        "metadata": {},
    },
    {
        "name": "NRO",
        "entity_type": "agency",
        "description": "National Reconnaissance Office. US intelligence agency responsible for design, build, launch, and operation of reconnaissance satellites. Its very existence was classified until 1992. Operates the nation's spy satellites and collects signals/imagery intelligence.",
        "aliases": "National Reconnaissance Office",
        "metadata": {},
    },
    {
        "name": "US Space Force",
        "entity_type": "agency",
        "description": "Sixth branch of the US Armed Forces, established December 20, 2019. Responsible for space operations including satellite communications, missile warning, and space domain awareness. Its creation formalized military space operations previously handled by Air Force Space Command.",
        "aliases": "USSF, Space Force, SPACE FORCE",
        "metadata": {},
    },
    {
        "name": "NOAA",
        "entity_type": "agency",
        "description": "National Oceanic and Atmospheric Administration. US agency focused on oceans and atmosphere. Involved in weather monitoring, climate research, and has connections to weather modification research and oversight. Key repository of atmospheric data.",
        "aliases": "National Oceanic and Atmospheric Administration",
        "metadata": {},
    },
    {
        "name": "USAF",
        "entity_type": "agency",
        "description": "United States Air Force. Has been the primary military branch involved in UAP investigation since Project Sign (1947), Project Grudge (1949), and Project Blue Book (1952-1969). Also operates weather modification capabilities and atmospheric research programs.",
        "aliases": "United States Air Force, US Air Force",
        "metadata": {},
    },
    {
        "name": "AMA",
        "entity_type": "organization",
        "description": "American Medical Association. Professional organization that has wielded enormous influence over US medical practice and education since the early 20th century. Under Morris Fishbein's leadership, systematically suppressed alternative medical practitioners and treatments.",
        "aliases": "American Medical Association",
        "metadata": {},
    },
    # ── PROGRAMS & FACILITIES ────────────────────────────────────
    {
        "name": "HAARP",
        "entity_type": "facility",
        "description": "High-frequency Active Auroral Research Program. Ionospheric research facility in Gakona, Alaska. Originally a joint USAF/Navy project, now operated by University of Alaska Fairbanks. Uses high-power radio transmitters to study the ionosphere. Based on Eastlund's patents. Subject of extensive weather modification conspiracy theories.",
        "aliases": "High-frequency Active Auroral Research Program",
        "metadata": {},
    },
    {
        "name": "SCoPEx",
        "entity_type": "program",
        "description": "Stratospheric Controlled Perturbation Experiment. Harvard solar geoengineering research project led by Frank Keutsch and David Keith. Aimed to test small-scale aerosol injection in the stratosphere. Faced massive opposition, particularly from Swedish indigenous groups. Project suspended.",
        "aliases": "Stratospheric Controlled Perturbation Experiment",
        "metadata": {},
    },
    # ── EVENTS & ARTIFACTS ───────────────────────────────────────
    {
        "name": "Roswell Incident",
        "entity_type": "event",
        "description": "July 1947 crash near Roswell, New Mexico. US Army initially announced recovery of a 'flying disc' before retracting to 'weather balloon.' Subject of multiple government investigations. The 1994 USAF report attributed debris to Project Mogul; the 1997 report addressed bodies as crash test dummies. Remains the foundational UAP event.",
        "aliases": "Roswell Crash, Roswell UFO Incident, Roswell 1947",
        "metadata": {},
    },
    {
        "name": "Nag Hammadi Library",
        "entity_type": "event",
        "description": "Collection of 13 Coptic codices discovered near Nag Hammadi, Egypt in 1945. Contains Gnostic texts including the Gospel of Thomas and the Gospel of Philip. Revealed early Christian diversity suppressed by orthodox authorities. Challenged the canonical narrative of Christian origins.",
        "aliases": "Nag Hammadi Codices, Nag Hammadi Scrolls",
        "metadata": {},
    },
    {
        "name": "Dead Sea Scrolls",
        "entity_type": "event",
        "description": "Ancient Jewish texts discovered in caves near Qumran, Dead Sea, beginning in 1947. Include the oldest known manuscripts of the Hebrew Bible. Publication was controlled by a small group of scholars for decades, fueling controversy over suppressed content and institutional gatekeeping.",
        "aliases": "Qumran Scrolls",
        "metadata": {},
    },
]

RELATIONSHIPS = []  # Relationships will be discovered by Gemini enrichment

ENTITY_SOURCES = {
    "Dario Amodei": [1439, 1465],
    "Sam Altman": [1442, 1463],
    "Mark Zuckerberg": [1464],
    "Abraham Flexner": [1415],
    "Morris Fishbein": [1415],
    "Ancel Keys": [1418],
    "John Yudkin": [1418],
    "Cristin Kearns": [1418],
    "Carroll Quigley": [1420],
    "Cecil Rhodes": [1436],
    "Bob Lazar": [1421],
    "Philip Corso": [1422],
    "Paul Hellyer": [1423],
    "Timothy Leary": [1424, 1447],
    "Ken Kesey": [1424, 1446],
    "Aldous Huxley": [1424],
    "R. Gordon Wasson": [1424],
    "Helena Blavatsky": [1443],
    "Alice Bailey": [1444],
    "Marilyn Ferguson": [1431],
    "Bernard J. Eastlund": [1427],
    "Karen Silkwood": [1429, 1438],
    "Mark Lombardi": [1437],
    "Enrico Mattei": [1434],
    "Wilhelm Reich": [1435],
    "John Perkins": [1432],
    "Muammar Gaddafi": [1419],
    "Hugo Chávez": [1419],
    "Walter Lippmann": [1417],
    "William Colby": [1419, 1452],
    "James Woolsey": [1453],
    "Leon Panetta": [1454],
    "John Brennan": [1455],
    "Michael Hayden": [1456],
    "David Petraeus": [1457],
    "James Clapper": [1459],
    "John Kerry": [1458],
    "Christopher Mellon": [1428],
    "David Keith": [1440],
    "Frank Keutsch": [1440],
    "Luke Iseman": [1460],
    "Alan Robock": [1430],
    "HAARP": [1425, 1426, 1427],
    "OpenAI": [1463],
    "Meta": [1464],
    "Anthropic": [1465],
    "Lucis Trust": [1444],
    "Esalen Institute": [1445],
    "Sandoz Labs": [1424],
    "Make Sunsets": [1460],
    "NRO": [1449],
    "US Space Force": [1448],
    "AFOSI": [1419],
    "SCoPEx": [1440],
    "Roswell Incident": [1422],
    "Nag Hammadi Library": [1461],
    "Dead Sea Scrolls": [1462],
    "Prince Bernhard": [1450],
    "John Foster Dulles": [1451],
}
